import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalsProviders from "./providers/GlobalsProviders";
import WebSocketProviders from "./providers/WebSocketProviders";
import { MicrophonePermissionDialog } from "@/app/components/features";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const websocketUrl =
    process.env.NEXT_PUBLIC_WEBSOCKET_URL ??
    "ws://localhost:3000/api/ws";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalsProviders>
          <WebSocketProviders url={websocketUrl}>
            {children}
            <MicrophonePermissionDialog />
          </WebSocketProviders>
        </GlobalsProviders>
      </body>
    </html>
  );
}
