import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalsProviders from "./providers/GlobalsProviders";
import WebSocketProviders from "./providers/WebSocketProviders";
import { MicrophonePermissionDialog } from "@/app/components/features";
import AuthProviders from "@/app/providers/AuthProviders";
import VideoProvider from "./providers/VideoProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const websocketUrl =
    process.env.NEXT_PUBLIC_SOCKET_SERVER_URL ??
    process.env.NEXT_PUBLIC_WEBSOCKET_URL ??
    "http://localhost:4000";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProviders>
          <GlobalsProviders>
            <VideoProvider>
              <WebSocketProviders url={websocketUrl}>
                {children}
                <MicrophonePermissionDialog />
              </WebSocketProviders>
            </VideoProvider>
          </GlobalsProviders>
        </AuthProviders>
      </body>
    </html>
  );
}
