import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalsProviders from "./providers/GlobalsProviders";
import WebSocketProviders from "./providers/WebSocketProviders";
import { MicrophonePermissionDialog } from "@/app/components/features";
import AuthProviders from "@/app/providers/AuthProviders";
import AnimationProvider from "./providers/AnimationProvider";
import RoastBattleProviders from "./providers/RoastBattleProviders";
import ResourceLoadingProvider from "./providers/ResourceLoadingProvider";
import ResourceLoadingGate from "./providers/ResourceLoadingProvider/ResourceLoadingGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 统一在入口处声明需要预加载的视频资源（public 下的文件直接用 /video/... 访问）
  const preloadVideoResources = ["/video/firework.mov", "/video/firework.webm"];
  const websocketUrl =
    process.env.NEXT_PUBLIC_SOCKET_SERVER_URL ??
    process.env.NEXT_PUBLIC_WEBSOCKET_URL ??
    "http://localhost:4000";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProviders>
          <GlobalsProviders>
            {/* 将视频资源加入预加载清单，确保加载遮罩阶段完成下载 */}
            <ResourceLoadingProvider resources={preloadVideoResources}>
              <AnimationProvider>
                <WebSocketProviders url={websocketUrl}>
                  <RoastBattleProviders>
                    <ResourceLoadingGate>{children}</ResourceLoadingGate>
                  </RoastBattleProviders>
                  <MicrophonePermissionDialog />
                </WebSocketProviders>
              </AnimationProvider>
            </ResourceLoadingProvider>
          </GlobalsProviders>
        </AuthProviders>
      </body>
    </html>
  );
}
